palavra = input('Digite algo:')
print(type(palavra))
print('É numérico?{}' .format(palavra.isnumeric()))
print('Tem espaço?{}' .format(palavra.isspace()))
print('É maiusculo?{}' .format(palavra.isupper()))
print('É minusculo?{}' .format(palavra.islower()))
print('É alfanumérico?{}' .format( palavra.isalnum()))
print('É alfabético?{}' .format(palavra.isalpha()))
print('Está capitalizada?{}' .format(palavra.istitle()))
