frase = str(input('Digite uma frase:')).upper()
frase = frase.strip()
print('A letra A aparece {} vezes na frase'.format(frase.count('A')))
print('A letra A apareceu pela primeira vez na posição {}'.format(frase.find('A')+1))
print('A ultima vez que aparece a letra A é na posição {}'.format(frase.rfind('A')+1)) 